spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: update